# Generated by Django 4.2.6 on 2023-10-31 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('subtitle', models.CharField(max_length=50, unique=True)),
                ('image', models.ImageField(upload_to='courses')),
                ('description', models.TextField()),
                ('fee', models.PositiveBigIntegerField()),
                ('is_active', models.BooleanField()),
            ],
        ),
    ]
