# Generated by Django 4.2.6 on 2023-10-31 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('text', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='courses',
            name='fee',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='is_active',
        ),
        migrations.AddField(
            model_name='courses',
            name='amounts',
            field=models.ManyToManyField(to='courses.amount'),
        ),
    ]
